name: Deploy to Azure App Service Free Tier

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: content-request-app    # Your app name (will be content-request-app.azurewebsites.net)
  NODE_VERSION: '18.x'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: Build MCP Server
      run: |
        cd mcp-server
        npm ci
        npm run build
        cd ..

    - name: Build Frontend
      env:
        VITE_API_URL: /api
        VITE_AZURE_CLIENT_ID: ${{ secrets.VITE_AZURE_CLIENT_ID }}
        VITE_AZURE_AUTHORITY: ${{ secrets.VITE_AZURE_AUTHORITY }}
      run: |
        npm ci
        npm run build

    - name: Create deployment package
      run: |
        # Create deployment directory
        mkdir -p deploy
        
        # Copy necessary files
        cp -r dist deploy/
        cp -r mcp-server/build deploy/mcp-server/build
        cp mcp-server/package*.json deploy/mcp-server/
        cp azure-server.js deploy/
        cp package*.json deploy/
        
        # Create a simple start script for Azure
        echo '#!/bin/bash' > deploy/startup.sh
        echo 'cd /home/site/wwwroot' >> deploy/startup.sh
        echo 'npm install --production' >> deploy/startup.sh
        echo 'cd mcp-server && npm install --production && cd ..' >> deploy/startup.sh
        echo 'node azure-server.js' >> deploy/startup.sh
        chmod +x deploy/startup.sh

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        package: deploy
        startup-command: 'bash startup.sh'

    - name: Azure logout
      run: |
        az logout
